Fake_Credentials:

  # Changeable
  firstname:
      - "james"
      - "mary"
      - "robert"
      - "patricia"
      - "john"
      - "jennifer"
      - "michael"
      - "linda"
      - "william"
      - "elizabeth"
      - "david"
      - "barbara"
      - "richard"
      - "susan"
      - "joseph"
      - "jessica"
      - "thomas"
      - "sarah"
      - "charles"
      - "karen"
      - "christopher"
      - "nancy"
      - "daniel"
      - "lisa"
      - "matthew"
      - "betty"
      - "anthony"
      - "margare"
      - "mark"
      - "sandra"
      - "donald"
      - "ashley"
      - "steven"
      - "kimberly"
      - "paul"
      - "emily"
      - "andrew"
      - "donna"
      - "joshua"
      - "michelle"
      - "kenneth"
      - "dorothy"
      - "kevin"
      - "carol"
      - "brian"
      - "amanda"
      - "george"
      - "melissa"
      - "edward"
      - "deborah"
      - "ronald"
      - "stephanie"
      - "timothy"
      - "rebecca"
      - "jason"
      - "sharon"
      - "jeffrey"
      - "laura"
      - "ryan"
      - "cynthia"
  
  # Changeable
  lastname:
      - "jacob"
      - "kathleen"
      - "gary"
      - "amy"
      - "nicholas"
      - "shirley"
      - "eric"
      - "angela"
      - "jonathan"
      - "helen"
      - "stephen"
      - "anna"
      - "larry"
      - "brenda"
      - "justin"
      - "pamela"
      - "scott"
      - "nicole"
      - "brandon"
      - "emma"
      - "benjamin"
      - "samantha"
      - "samuel"
      - "katherine"
      - "gregory"
      - "christine"
      - "frank"
      - "debr"
      - "alexander"
      - "rachel"
      - "raymond"
      - "catherine"
      - "patrick"
      - "carolyn"
      - "jack"
      - "janet"
      - "dennis"
      - "ruth"
      - "jerry"
      - "maria"
      - "tyler"
      - "heather"
      - "aaron"
      - "diane"
      - "jose"
      - "virginia"
      - "adam"
      - "julie"
      - "henry"
      - "joyce"
      - "nathan"
      - "victoria"
      - "douglas"
      - "olivia"
      - "zachary"
      - "kelly"
      - "peter"
      - "christina"
      - "kyle"
      - "lauren"

  # Changeable
  extra:
      - "community"
      - "help"
      - "support"
      - "gaming"
      - "admin"
      - "team"
      - "group"
  
  # DO NOT CHANGE THIS, IT WILL MAKE YOUR GENERATED EMAILS LOOKS INVALID!!!
  punctuations:
      - "-"
      - "."
      - "_"
      - ""
  
  # Changeable
  emails:
      - "gmail"
      - "outlook"
      - "yahoo"
      - "horde"
      - "samsung"
      - "vivo"
      - "oppo"

  # Changeable
  company:
      - "lulz"
      - "crocks"
      - "minions"
      - "genteng"
      - "lienshng"
      - "kiss"
      - "lips"
  
  # Changeable
  domain:
      - "com"
      - "me"
      - "tk"
      - "msn"
      - "shop"
      - "xyz"

  # Changeable
  password:
      - "123456789"
      - "987654321"
      - "qwerty"
      - "QWERTY"
      - "dragon"
      - "DRAGON"
      - "Admin"
      - "User"
      - "Windows"
      - "Linux"
      - "Android"
      - "Apple"
      - "ILoveYou"
      - "LoveLetter"
      - "Hentai"
      - "Heaven"
      - "ILove"
      - "IHate"
      - "Dirt"

  # Changeable
  symbols:
      - "!"
      - "#"
      - "$"
      - "%"
      - "^"
      - "&"
      - "*"
      - "("
      - ")"
      - ">"
      - "<"
      - "?"
      - "/"
      - '\'
      - '"'
      - "'"
      - " "
